export const PASSIONS = [
  { id:"football",   label:"Football",   emoji:"⚽", color:"#FF6B2B" },
  { id:"cricket",    label:"Cricket",    emoji:"🏏", color:"#22C97A" },
  { id:"music",      label:"Music",      emoji:"🎵", color:"#C084FC" },
  { id:"dance",      label:"Dance",      emoji:"💃", color:"#FF6B9D" },
  { id:"gaming",     label:"Gaming",     emoji:"🎮", color:"#3B9EFF" },
  { id:"basketball", label:"Basketball", emoji:"🏀", color:"#FF8C00" },
  { id:"cooking",    label:"Cooking",    emoji:"🍳", color:"#FF4757" },
  { id:"swimming",   label:"Swimming",   emoji:"🏊", color:"#22D3EE" },
  { id:"chess",      label:"Chess",      emoji:"♟️", color:"#818CF8" },
  { id:"badminton",  label:"Badminton",  emoji:"🏸", color:"#FB923C" },
];
export const SYLLABI = [
  { id:"cbse", label:"CBSE", desc:"Central Board of Secondary Education", color:"#FF6B2B" },
  { id:"icse", label:"ICSE", desc:"Indian Certificate of Secondary Education", color:"#9333EA" },
  { id:"ssc",  label:"SSC",  desc:"State Secondary Certificate — Pick your state", color:"#16A34A" },
];

export const SSC_STATES = [
  { id:"telangana",     label:"Telangana",      emoji:"🏙️" },
  { id:"andhrapradesh", label:"Andhra Pradesh",  emoji:"🌊" },
  { id:"maharashtra",   label:"Maharashtra",     emoji:"🏛️" },
  { id:"karnataka",     label:"Karnataka",       emoji:"🌿" },
  { id:"tamilnadu",     label:"Tamil Nadu",      emoji:"🏺" },
  { id:"kerala",        label:"Kerala",          emoji:"🌴" },
  { id:"gujarat",       label:"Gujarat",         emoji:"🦁" },
  { id:"rajasthan",     label:"Rajasthan",       emoji:"🏜️" },
  { id:"uttarpradesh",  label:"Uttar Pradesh",   emoji:"🕌" },
  { id:"westbengal",    label:"West Bengal",     emoji:"🐯" },
];

export const SSC_CURRICULUM = {
  telangana: {
    subjects: [
      { id:"maths",    label:"Mathematics",  emoji:"➗" },
      { id:"science",  label:"Science",      emoji:"🔬" },
      { id:"social",   label:"Social Studies",emoji:"🌍" },
      { id:"english",  label:"English",      emoji:"📝" },
      { id:"telugu",   label:"Telugu",       emoji:"🅃" },
    ],
    topics: {
      maths: {
        6:  ["Real Numbers","Whole Numbers","Integers","Fractions and Decimals","Data Handling","Simple Equations","Lines and Angles","Triangles","Comparing Quantities","Rational Numbers","Practical Geometry","Perimeter and Area","Algebraic Expressions"],
        7:  ["Integers","Fractions and Decimals","Data Handling","Simple Equations","Lines and Angles","The Triangle","Congruence","Comparing Quantities","Rational Numbers","Practical Geometry","Perimeter and Area","Algebraic Expressions","Visualising Solid Shapes"],
        8:  ["Rational Numbers","Linear Equations","Quadrilaterals","Data Handling","Squares and Square Roots","Cubes and Cube Roots","Comparing Quantities","Algebraic Expressions","Mensuration","Exponents","Direct and Inverse Proportion","Factorisation","Graphs"],
        9:  ["Real Numbers","Polynomials","Linear Equations in Two Variables","Lines and Angles","Triangles","Coordinate Geometry","Heron's Formula","Surface Areas and Volumes","Statistics","Probability"],
        10: ["Real Numbers","Polynomials","Pair of Linear Equations","Quadratic Equations","Arithmetic Progressions","Triangles","Coordinate Geometry","Trigonometry","Applications of Trigonometry","Circles","Areas Related to Circles","Surface Areas and Volumes","Statistics","Probability"],
      },
      science: {
        6:  ["Food: Sources and Components","Fibre to Fabric","Sorting Materials","Separation of Substances","Changes Around Us","Plants","Body Movements","Motion and Measurement","Light and Shadows","Electricity","Magnets","Water","Air","Garbage"],
        7:  ["Nutrition in Plants","Nutrition in Animals","Fibre to Fabric","Heat","Acids and Bases","Physical and Chemical Changes","Weather and Climate","Winds and Storms","Soil","Respiration","Transportation","Reproduction in Plants","Motion and Time","Electric Current","Light","Water","Forests"],
        8:  ["Crop Production","Microorganisms","Synthetic Fibres","Metals and Non-Metals","Coal and Petroleum","Combustion","Conservation of Plants","Cell","Reproduction in Animals","Adolescence","Force and Pressure","Friction","Sound","Chemical Effects","Natural Phenomena","Light","Stars and Solar System","Pollution"],
        9:  ["Matter","Atoms and Molecules","Structure of Atom","Cell — Unit of Life","Tissues","Diversity in Living Organisms","Motion","Force and Laws of Motion","Gravitation","Work and Energy","Sound","Why Do We Fall Ill","Natural Resources"],
        10: ["Chemical Reactions","Acids Bases and Salts","Metals and Non-Metals","Carbon Compounds","Periodic Classification","Life Processes","Control and Coordination","Reproduction","Heredity and Evolution","Light","Human Eye","Electricity","Magnetic Effects","Sources of Energy","Our Environment"],
      },
      social: {
        6:  ["What is History","Early Humans","Agriculture and Settlements","Ancient Civilisations","Vedic Period","Kingdoms and Republics","New Religious Ideas","The Mauryan Empire","After the Mauryas","Globe and Maps","Interior of the Earth","Landforms","Water Bodies","Climate","Natural Vegetation","India — Our Country"],
        7:  ["Sources of Medieval History","Establishment of Delhi Sultanate","Vijayanagara Empire","Mughal Empire","Bhakti Movement","Sufism","Medieval Architecture","Interior of the Earth","Rocks","Weathering","India — Rivers","India — Climate","India — Forests","India — Agriculture","Democracy","State Government"],
        8:  ["Modern Age in Europe","Industrial Revolution","Social and Religious Reform","British Rule in India","1857 Revolt","Nationalism in India","Freedom Movement","New Empires","Atmosphere","Water Resources","India — Mineral Resources","India — Industries","India — Transport","Indian Constitution","Fundamental Rights","Secularism"],
        9:  ["Telangana — History and Culture","The French Revolution","Russian Revolution","World Between Two Wars","National Movement — Early Phase","National Movement — Mass Phase","World After World War II","Our Universe","India — Location and Relief","India — Climate and Vegetation","India — Water Resources","India — Agriculture","India — Industries","Democracy","Electoral Process","State Government in India"],
        10: ["Telangana — Formation and Development","Nationalism in India — Gandhian Era","World War II and After","Independence of India","The World After Independence","Globalisation","India — Strategic Position","India — Population","India — Economy","India — Development","Indian Constitution","Indian Government","Social Issues","Environment"],
      },
      english: {
        6:  ["Reading Comprehension","Grammar — Parts of Speech","Grammar — Tenses","Vocabulary","Letter Writing","Composition","Literature Appreciation"],
        7:  ["Reading Skills","Grammar — Sentences","Grammar — Voice and Narration","Vocabulary Building","Essay Writing","Formal Letters","Literature"],
        8:  ["Reading Comprehension","Grammar — Advanced Tenses","Transformation of Sentences","Vocabulary","Report Writing","Formal and Informal Letters","Prose and Poetry"],
        9:  ["Reading Comprehension","Grammar — Clauses","Grammar — Error Correction","Vocabulary","Essay Writing","Letter Writing","Prose and Poetry Appreciation"],
        10: ["Reading Comprehension","Grammar — All Structures","Vocabulary — Idioms and Phrases","Essay Writing","Letter and Email Writing","Précis Writing","Prose Poetry and Drama"],
      },
      telugu: {
        6:  ["పద్యాలు (Poems)","గద్యాలు (Prose)","వ్యాకరణం — సంధి","వ్యాకరణం — సమాసాలు","రచన — వ్యాస రచన","రచన — లేఖ రచన"],
        7:  ["పద్యభాగాలు","గద్యభాగాలు","వ్యాకరణం — కారకాలు","వ్యాకరణం — అలంకారాలు","రచన — కథా రచన","రచన — సంభాషణ"],
        8:  ["కవిత్వం","వచన సాహిత్యం","వ్యాకరణం — వాచ్యాలు","వ్యాకరణం — సమాసాలు","రచన — వర్ణన రచన","రచన — నివేదిక"],
        9:  ["పద్య సాహిత్యం","గద్య సాహిత్యం","వ్యాకరణం — విస్తృత అధ్యయనం","భాషా నైపుణ్యాలు","రచన — వ్యాసాలు","రచన — లేఖలు"],
        10: ["పద్య సాహిత్యం","గద్య సాహిత్యం","నాటక సాహిత్యం","వ్యాకరణం — సమగ్ర అధ్యయనం","రచన — వ్యాసాలు","రచన — అనువాదం","పరీక్షా సన్నద్ధత"],
      },
    },
  },
  andhrapradesh: {
    subjects: [
      { id:"maths",   label:"Mathematics",   emoji:"➗" },
      { id:"science", label:"Science",        emoji:"🔬" },
      { id:"social",  label:"Social Studies", emoji:"🌍" },
      { id:"english", label:"English",        emoji:"📝" },
      { id:"telugu",  label:"Telugu",         emoji:"🅃" },
    ],
    topics: {
      maths: {
        6:  ["Real Numbers","Integers","Fractions","Decimals","Data Handling","Algebra Basics","Geometry","Mensuration","Ratio and Proportion"],
        7:  ["Integers","Fractions and Decimals","Simple Equations","Lines and Angles","Triangles","Comparing Quantities","Algebraic Expressions","Practical Geometry","Perimeter and Area"],
        8:  ["Rational Numbers","Linear Equations","Quadrilaterals","Squares and Square Roots","Cubes and Cube Roots","Mensuration","Algebraic Expressions","Factorisation","Exponents"],
        9:  ["Real Numbers","Polynomials","Linear Equations","Triangles","Coordinate Geometry","Statistics","Probability","Surface Areas and Volumes"],
        10: ["Real Numbers","Polynomials","Quadratic Equations","Arithmetic Progressions","Triangles","Coordinate Geometry","Trigonometry","Circles","Mensuration","Statistics","Probability"],
      },
      science: {
        6:  ["Food","Fibre to Fabric","Sorting Materials","Changes Around Us","Plants","Body Movements","Motion","Light","Electricity","Water","Air"],
        7:  ["Nutrition","Heat","Acids and Bases","Physical Changes","Weather","Soil","Respiration","Motion","Light","Water","Forests"],
        8:  ["Crop Production","Microorganisms","Metals and Non-metals","Combustion","Cell","Reproduction","Force and Pressure","Sound","Light","Pollution"],
        9:  ["Matter","Atoms","Structure of Atom","Cell","Tissues","Motion","Force","Gravitation","Work and Energy","Sound","Natural Resources"],
        10: ["Chemical Reactions","Acids Bases Salts","Metals and Non-metals","Carbon","Periodic Table","Life Processes","Reproduction","Heredity","Light","Electricity","Environment"],
      },
      social: {
        6:  ["History: Early Humans","History: Ancient Civilisations","Geography: Globe and Maps","Geography: Earth","Civics: Our Government"],
        7:  ["History: Medieval India","History: Vijayanagara","Geography: India","Civics: Democracy"],
        8:  ["History: Modern India","History: Freedom Movement","Geography: Resources","Civics: Constitution"],
        9:  ["History: National Movement","Geography: AP Location","Geography: AP Resources","Civics: State Government"],
        10: ["History: Independent India","Geography: India Economy","Geography: AP Development","Civics: Indian Government","Economics: Development"],
      },
      english: {
        6:  ["Reading","Grammar","Vocabulary","Writing","Literature"],
        7:  ["Reading Skills","Grammar","Vocabulary","Essay Writing","Literature"],
        8:  ["Comprehension","Advanced Grammar","Vocabulary","Report Writing","Literature"],
        9:  ["Reading","Grammar","Vocabulary","Essay and Letters","Prose and Poetry"],
        10: ["Comprehension","Grammar","Vocabulary","Writing Skills","Prose Poetry Drama"],
      },
      telugu: {
        6:  ["పద్యాలు","గద్యాలు","వ్యాకరణం","రచన"],
        7:  ["పద్యభాగాలు","గద్యభాగాలు","వ్యాకరణం","రచన"],
        8:  ["కవిత్వం","వచన సాహిత్యం","వ్యాకరణం","రచన"],
        9:  ["పద్య సాహిత్యం","గద్య సాహిత్యం","వ్యాకరణం","రచన"],
        10: ["పద్య సాహిత్యం","గద్య సాహిత్యం","నాటకం","వ్యాకరణం","రచన"],
      },
    },
  },
  maharashtra: {
    subjects: [
      { id:"maths",    label:"Mathematics",   emoji:"➗" },
      { id:"science",  label:"Science",        emoji:"🔬" },
      { id:"social",   label:"Social Science", emoji:"🌍" },
      { id:"english",  label:"English",        emoji:"📝" },
      { id:"marathi",  label:"Marathi",        emoji:"🌺" },
    ],
    topics: {
      maths: {
        6:  ["Natural Numbers","Integers","Fractions","Decimals","Ratio and Proportion","Simple Equations","Geometry","Mensuration","Data Handling"],
        7:  ["Integers","Fractions","Equations","Lines and Angles","Triangles","Algebraic Expressions","Mensuration","Statistics"],
        8:  ["Rational Numbers","Powers and Exponents","Equations","Factorisation","Quadrilaterals","Statistics","Mensuration","Graphs"],
        9:  ["Real Numbers","Polynomials","Linear Equations","Triangles","Statistics","Trigonometry","Coordinate Geometry","Surface Areas"],
        10: ["Algebra","Geometry","Trigonometry","Mensuration","Statistics and Probability","Coordinate Geometry","Financial Planning"],
      },
      science: {
        6:  ["Food and Nutrition","Fibre to Fabric","Sorting Materials","Changes","Plants","Body","Motion","Light","Electricity","Water","Air"],
        7:  ["Nutrition","Heat","Acids and Bases","Changes","Weather","Soil","Respiration","Transport","Motion","Electric Current","Light"],
        8:  ["Crop Production","Microorganisms","Metals","Combustion","Cell","Reproduction","Force","Sound","Chemical Effects","Pollution"],
        9:  ["Laws of Motion","Work and Energy","Current Electricity","Measurement","Acids Bases Salts","Carbon Compounds","Classification of Plants","Reflection of Light","Refractive Index","Carbon Compounds"],
        10: ["Gravitation","Periodic Classification","Chemical Reactions","Electricity","Magnetism","Space Missions","Carbon","Life Processes","Heredity","Light"],
      },
      social: {
        6:  ["History: Ancient India","Geography: The Earth","Civics: Government"],
        7:  ["History: Medieval India","Geography: Maharashtra","Civics: Democracy"],
        8:  ["History: Modern India","Geography: Resources","Civics: Constitution"],
        9:  ["History: Modern World","Geography: India","Civics: State Government","Economics: Development"],
        10: ["History: India After Independence","Geography: Economic Geography","Civics: Government","Economics: Maharashtra Economy"],
      },
      english: {
        6:  ["Reading","Grammar","Vocabulary","Writing","Literature"],
        7:  ["Reading Skills","Grammar","Vocabulary","Essay","Literature"],
        8:  ["Comprehension","Grammar","Vocabulary","Writing","Literature"],
        9:  ["Reading","Grammar","Vocabulary","Writing","Prose and Poetry"],
        10: ["Comprehension","Grammar","Vocabulary","Writing","Prose Poetry Drama"],
      },
      marathi: {
        6:  ["कविता","गद्य","व्याकरण","लेखन"],
        7:  ["कविता","गद्य","व्याकरण","निबंध लेखन"],
        8:  ["कविता","गद्य","व्याकरण","पत्र लेखन"],
        9:  ["कविता","गद्य","नाटक","व्याकरण","लेखन"],
        10: ["कविता","गद्य","नाटक","व्याकरण","लेखन","भाषा अभ्यास"],
      },
    },
  },
  karnataka: {
    subjects: [
      { id:"maths",    label:"Mathematics",   emoji:"➗" },
      { id:"science",  label:"Science",        emoji:"🔬" },
      { id:"social",   label:"Social Science", emoji:"🌍" },
      { id:"english",  label:"English",        emoji:"📝" },
      { id:"kannada",  label:"Kannada",        emoji:"🌸" },
    ],
    topics: {
      maths: {
        6:  ["Number System","Integers","Fractions","Decimals","Mensuration","Algebra","Ratio","Data Handling","Geometry"],
        7:  ["Integers","Fractions","Algebra","Lines and Angles","Triangles","Comparing Quantities","Mensuration","Data Handling"],
        8:  ["Rational Numbers","Algebra","Geometry","Mensuration","Statistics","Exponents","Factorisation"],
        9:  ["Number Systems","Polynomials","Coordinate Geometry","Linear Equations","Triangles","Statistics","Surface Areas"],
        10: ["Real Numbers","Polynomials","Quadratic Equations","Arithmetic Progressions","Triangles","Trigonometry","Statistics","Probability","Mensuration"],
      },
      science: {
        6:  ["Food","Fibre","Sorting Materials","Changes","Plants","Body","Motion","Light","Electricity","Water","Air"],
        7:  ["Nutrition","Heat","Acids Bases","Changes","Weather","Soil","Motion","Light","Electric Current"],
        8:  ["Crop Production","Microorganisms","Metals","Combustion","Cell","Force","Sound","Pollution"],
        9:  ["Matter","Atoms","Atom Structure","Cell","Tissues","Motion","Force","Gravitation","Work Energy","Sound"],
        10: ["Chemical Reactions","Acids Bases Salts","Metals","Carbon","Periodic Table","Life Processes","Reproduction","Light","Electricity","Environment"],
      },
      social: {
        6:  ["History: Ancient Karnataka","Geography: Earth","Civics: Government"],
        7:  ["History: Medieval Karnataka","Geography: Karnataka","Civics: Democracy"],
        8:  ["History: Modern India","Geography: Resources","Civics: Constitution"],
        9:  ["History: Freedom Struggle","Geography: India","Civics: Government"],
        10: ["History: Independent India","Geography: Economic Geography","Civics: Democracy","Economics: Karnataka Development"],
      },
      english: {
        6:  ["Reading","Grammar","Vocabulary","Writing","Literature"],
        7:  ["Reading","Grammar","Vocabulary","Essay","Literature"],
        8:  ["Comprehension","Grammar","Vocabulary","Writing","Literature"],
        9:  ["Reading","Grammar","Vocabulary","Writing","Prose and Poetry"],
        10: ["Comprehension","Grammar","Vocabulary","Writing","Prose Poetry Drama"],
      },
      kannada: {
        6:  ["ಪದ್ಯ","ಗದ್ಯ","ವ್ಯಾಕರಣ","ಲೇಖನ"],
        7:  ["ಕವಿತೆ","ಗದ್ಯ","ವ್ಯಾಕರಣ","ಪ್ರಬಂಧ"],
        8:  ["ಕವಿತೆ","ಗದ್ಯ","ವ್ಯಾಕರಣ","ಪತ್ರ ಲೇಖನ"],
        9:  ["ಕವಿತೆ","ಗದ್ಯ","ನಾಟಕ","ವ್ಯಾಕರಣ","ಲೇಖನ"],
        10: ["ಕವಿತೆ","ಗದ್ಯ","ನಾಟಕ","ವ್ಯಾಕರಣ","ಲೇಖನ","ಭಾಷಾ ಅಭ್ಯಾಸ"],
      },
    },
  },
  tamilnadu: {
    subjects: [
      { id:"maths",   label:"Mathematics",   emoji:"➗" },
      { id:"science", label:"Science",        emoji:"🔬" },
      { id:"social",  label:"Social Science", emoji:"🌍" },
      { id:"english", label:"English",        emoji:"📝" },
      { id:"tamil",   label:"Tamil",          emoji:"🌟" },
    ],
    topics: {
      maths: {
        6:  ["Numbers","Integers","Fractions","Decimals","Ratio","Geometry","Mensuration","Algebra","Statistics"],
        7:  ["Number Theory","Percentage","Algebra","Geometry","Mensuration","Graphs","Statistics"],
        8:  ["Rational Numbers","Algebra","Geometry","Practical Geometry","Statistics","Life Mathematics"],
        9:  ["Set Language","Real Numbers","Algebra","Geometry","Coordinate Geometry","Trigonometry","Statistics","Probability"],
        10: ["Relations and Functions","Numbers and Sequences","Algebra","Geometry","Coordinate Geometry","Trigonometry","Mensuration","Statistics","Probability"],
      },
      science: {
        6:  ["Food","Fibre","Sorting Materials","Changes","Plants","Body","Motion","Light","Electricity","Water","Air"],
        7:  ["Nutrition","Respiration","Transport","Reproduction","Heredity","Physics Basics","Chemistry Basics"],
        8:  ["Crop Production","Microorganisms","Metals","Combustion","Cell","Force","Sound","Pollution","Light"],
        9:  ["Matter","Scientific Laws","Atoms","Cell Biology","Tissues","Motion","Force","Gravitation","Health"],
        10: ["Laws of Motion","Optics","Thermal Physics","Electricity","Nuclear Physics","Periodic Table","Carbon","Plant Kingdom","Animal Kingdom","Genetics"],
      },
      social: {
        6:  ["History: Prehistoric Times","History: Early Civilisations","Geography: The Universe","Civics: Our Government"],
        7:  ["History: Medieval Tamil Nadu","Geography: Weather and Climate","Civics: Democracy"],
        8:  ["History: Colonial India","History: Freedom Movement","Geography: Resources","Civics: Constitution"],
        9:  ["History: 19th Century","History: Tamil Nadu Freedom Struggle","Geography: India","Civics: Election"],
        10: ["History: World History","History: India Since Independence","Geography: Economic Geography","Civics: UN and India","Economics: TN Development"],
      },
      english: {
        6:  ["Reading","Grammar","Vocabulary","Writing","Literature"],
        7:  ["Reading Skills","Grammar","Vocabulary","Essay","Literature"],
        8:  ["Comprehension","Grammar","Vocabulary","Writing","Literature"],
        9:  ["Reading","Grammar","Vocabulary","Writing","Prose and Poetry"],
        10: ["Comprehension","Grammar","Vocabulary","Writing","Prose Poetry Drama"],
      },
      tamil: {
        6:  ["கவிதை","உரைநடை","இலக்கணம்","எழுத்து"],
        7:  ["கவிதை","உரைநடை","இலக்கணம்","கட்டுரை"],
        8:  ["கவிதை","உரைநடை","இலக்கணம்","கடிதம்"],
        9:  ["கவிதை","உரைநடை","நாடகம்","இலக்கணம்","எழுத்து"],
        10: ["கவிதை","உரைநடை","நாடகம்","இலக்கணம்","எழுத்து","மொழி"],
      },
    },
  },
  kerala: {
    subjects: [
      { id:"maths",    label:"Mathematics",   emoji:"➗" },
      { id:"science",  label:"Science",        emoji:"🔬" },
      { id:"social",   label:"Social Science", emoji:"🌍" },
      { id:"english",  label:"English",        emoji:"📝" },
      { id:"malayalam",label:"Malayalam",      emoji:"🌊" },
    ],
    topics: {
      maths: {
        6:  ["Numbers","Integers","Fractions","Decimals","Geometry","Mensuration","Algebra","Ratio","Statistics"],
        7:  ["Number Theory","Algebra","Geometry","Mensuration","Statistics","Percentage"],
        8:  ["Rational Numbers","Algebra","Geometry","Mensuration","Statistics","Probability"],
        9:  ["Polynomials","Linear Equations","Coordinate Geometry","Triangles","Statistics","Probability"],
        10: ["Arithmetic Sequences","Circles","Mathematics of Chance","Polynomials","Trigonometry","Coordinate Geometry","Statistics"],
      },
      science: {
        6:  ["Food and Health","Fibre","Materials","Changes","Plants","Body","Light","Electricity","Water","Air"],
        7:  ["Nutrition","Heat","Acids Bases","Changes","Weather","Soil","Motion","Light","Electric Current"],
        8:  ["Crop Production","Microorganisms","Metals","Combustion","Cell","Force","Sound","Pollution"],
        9:  ["Matter","Atoms","Structure of Atom","Cell","Tissues","Motion","Force","Gravitation","Energy"],
        10: ["Chemical Reactions","Acids Bases Salts","Metals","Carbon","Periodic Table","Life Processes","Reproduction","Light","Electricity","Environment"],
      },
      social: {
        6:  ["History: Ancient Kerala","Geography: Earth","Civics: Government"],
        7:  ["History: Medieval Kerala","Geography: Kerala","Civics: Democracy"],
        8:  ["History: Modern India","Geography: Resources","Civics: Constitution"],
        9:  ["History: Freedom Struggle","Geography: India","Civics: Government","Economics: Kerala"],
        10: ["History: Independent India","Geography: Economic Geography","Civics: Democracy","Economics: Development"],
      },
      english: {
        6:  ["Reading","Grammar","Vocabulary","Writing","Literature"],
        7:  ["Reading Skills","Grammar","Vocabulary","Essay","Literature"],
        8:  ["Comprehension","Grammar","Vocabulary","Writing","Literature"],
        9:  ["Reading","Grammar","Vocabulary","Writing","Prose and Poetry"],
        10: ["Comprehension","Grammar","Vocabulary","Writing","Prose Poetry Drama"],
      },
      malayalam: {
        6:  ["കവിത","ഗദ്യം","വ്യാകരണം","രചന"],
        7:  ["കവിത","ഗദ്യം","വ്യാകരണം","ഉപന്യാസം"],
        8:  ["കവിത","ഗദ്യം","വ്യാകരണം","കത്ത്"],
        9:  ["കവിത","ഗദ്യം","നാടകം","വ്യാകരണം","രചന"],
        10: ["കവിത","ഗദ്യം","നാടകം","വ്യാകരണം","രചന","ഭാഷാ പഠനം"],
      },
    },
  },
  gujarat: {
    subjects: [
      { id:"maths",    label:"Mathematics",   emoji:"➗" },
      { id:"science",  label:"Science",        emoji:"🔬" },
      { id:"social",   label:"Social Science", emoji:"🌍" },
      { id:"english",  label:"English",        emoji:"📝" },
      { id:"gujarati", label:"Gujarati",       emoji:"🌻" },
    ],
    topics: {
      maths: {
        6:["Numbers","Integers","Fractions","Decimals","Algebra","Geometry","Mensuration","Data Handling"],
        7:["Integers","Fractions","Equations","Lines and Angles","Triangles","Algebraic Expressions","Mensuration"],
        8:["Rational Numbers","Algebra","Geometry","Mensuration","Statistics","Exponents"],
        9:["Real Numbers","Polynomials","Linear Equations","Triangles","Statistics","Surface Areas"],
        10:["Real Numbers","Quadratic Equations","Arithmetic Progressions","Triangles","Trigonometry","Statistics","Probability","Mensuration"],
      },
      science: {
        6:["Food","Materials","Changes","Plants","Body","Motion","Light","Electricity","Water","Air"],
        7:["Nutrition","Heat","Acids Bases","Changes","Weather","Soil","Motion","Light"],
        8:["Crop Production","Microorganisms","Metals","Combustion","Cell","Force","Sound","Pollution"],
        9:["Matter","Atoms","Cell","Tissues","Motion","Force","Gravitation","Work Energy"],
        10:["Chemical Reactions","Acids Bases Salts","Metals","Carbon","Periodic Table","Life Processes","Reproduction","Light","Electricity","Environment"],
      },
      social: {
        6:["History: Ancient India","Geography: Earth","Civics: Government"],
        7:["History: Medieval India","Geography: Gujarat","Civics: Democracy"],
        8:["History: Modern India","Geography: Resources","Civics: Constitution"],
        9:["History: Freedom Struggle","Geography: India","Civics: Government"],
        10:["History: Independent India","Geography: Economic Geography","Civics: Democracy","Economics: Gujarat Economy"],
      },
      english: {
        6:["Reading","Grammar","Vocabulary","Writing","Literature"],
        7:["Reading Skills","Grammar","Vocabulary","Essay","Literature"],
        8:["Comprehension","Grammar","Vocabulary","Writing","Literature"],
        9:["Reading","Grammar","Vocabulary","Writing","Prose and Poetry"],
        10:["Comprehension","Grammar","Vocabulary","Writing","Prose Poetry Drama"],
      },
      gujarati: {
        6:["કવિતા","ગદ્ય","વ્યાકરણ","લેખન"],
        7:["કવિતા","ગદ્ય","વ્યાકરણ","નિબંધ"],
        8:["કવિતા","ગદ્ય","વ્યાકરણ","પત્ર"],
        9:["કવિતા","ગદ્ય","નાટક","વ્યાકરણ","લેખન"],
        10:["કવિતા","ગદ્ય","નાટક","વ્યાકરણ","લેખન","ભાષા"],
      },
    },
  },
  rajasthan: {
    subjects: [
      { id:"maths",   label:"Mathematics",   emoji:"➗" },
      { id:"science", label:"Science",        emoji:"🔬" },
      { id:"social",  label:"Social Science", emoji:"🌍" },
      { id:"english", label:"English",        emoji:"📝" },
      { id:"hindi",   label:"Hindi",          emoji:"🇮🇳" },
    ],
    topics: {
      maths: {
        6:["Numbers","Integers","Fractions","Decimals","Algebra","Geometry","Mensuration","Data Handling"],
        7:["Integers","Fractions","Equations","Lines and Angles","Triangles","Algebraic Expressions","Mensuration"],
        8:["Rational Numbers","Algebra","Geometry","Mensuration","Statistics","Exponents"],
        9:["Real Numbers","Polynomials","Linear Equations","Triangles","Statistics","Surface Areas"],
        10:["Real Numbers","Quadratic Equations","Arithmetic Progressions","Triangles","Trigonometry","Statistics","Probability","Mensuration"],
      },
      science: {
        6:["Food","Materials","Changes","Plants","Body","Motion","Light","Electricity","Water","Air"],
        7:["Nutrition","Heat","Acids Bases","Changes","Weather","Soil","Motion","Light"],
        8:["Crop Production","Microorganisms","Metals","Combustion","Cell","Force","Sound","Pollution"],
        9:["Matter","Atoms","Cell","Tissues","Motion","Force","Gravitation","Work Energy"],
        10:["Chemical Reactions","Acids Bases Salts","Metals","Carbon","Periodic Table","Life Processes","Reproduction","Light","Electricity","Environment"],
      },
      social: {
        6:["History: Ancient India","Geography: Earth","Civics: Government"],
        7:["History: Medieval India","Geography: Rajasthan","Civics: Democracy"],
        8:["History: Modern India","Geography: Resources","Civics: Constitution"],
        9:["History: Freedom Struggle","Geography: India","Civics: Government"],
        10:["History: Independent India","Geography: Economic Geography","Civics: Democracy","Economics: Rajasthan Economy"],
      },
      english: {
        6:["Reading","Grammar","Vocabulary","Writing","Literature"],
        7:["Reading Skills","Grammar","Vocabulary","Essay","Literature"],
        8:["Comprehension","Grammar","Vocabulary","Writing","Literature"],
        9:["Reading","Grammar","Vocabulary","Writing","Prose and Poetry"],
        10:["Comprehension","Grammar","Vocabulary","Writing","Prose Poetry Drama"],
      },
      hindi: {
        6:["कविता","गद्य","व्याकरण","लेखन"],
        7:["कविता","गद्य","व्याकरण","निबंध"],
        8:["कविता","गद्य","व्याकरण","पत्र लेखन"],
        9:["कविता","गद्य","नाटक","व्याकरण","लेखन"],
        10:["कविता","गद्य","नाटक","व्याकरण","लेखन","भाषा अभ्यास"],
      },
    },
  },
  uttarpradesh: {
    subjects: [
      { id:"maths",   label:"Mathematics",   emoji:"➗" },
      { id:"science", label:"Science",        emoji:"🔬" },
      { id:"social",  label:"Social Science", emoji:"🌍" },
      { id:"english", label:"English",        emoji:"📝" },
      { id:"hindi",   label:"Hindi",          emoji:"🇮🇳" },
    ],
    topics: {
      maths: {
        6:["Numbers","Integers","Fractions","Decimals","Algebra","Geometry","Mensuration","Data Handling"],
        7:["Integers","Fractions","Equations","Lines and Angles","Triangles","Algebraic Expressions","Mensuration"],
        8:["Rational Numbers","Algebra","Geometry","Mensuration","Statistics","Exponents"],
        9:["Real Numbers","Polynomials","Linear Equations","Triangles","Statistics","Surface Areas"],
        10:["Real Numbers","Quadratic Equations","Arithmetic Progressions","Triangles","Trigonometry","Statistics","Probability","Mensuration"],
      },
      science: {
        6:["Food","Materials","Changes","Plants","Body","Motion","Light","Electricity","Water","Air"],
        7:["Nutrition","Heat","Acids Bases","Changes","Weather","Soil","Motion","Light"],
        8:["Crop Production","Microorganisms","Metals","Combustion","Cell","Force","Sound","Pollution"],
        9:["Matter","Atoms","Cell","Tissues","Motion","Force","Gravitation","Work Energy"],
        10:["Chemical Reactions","Acids Bases Salts","Metals","Carbon","Periodic Table","Life Processes","Reproduction","Light","Electricity","Environment"],
      },
      social: {
        6:["History: Ancient India","Geography: Earth","Civics: Government"],
        7:["History: Medieval India","Geography: UP","Civics: Democracy"],
        8:["History: Modern India","Geography: Resources","Civics: Constitution"],
        9:["History: Freedom Struggle","Geography: India","Civics: Government"],
        10:["History: Independent India","Geography: Economic Geography","Civics: Democracy","Economics: UP Economy"],
      },
      english: {
        6:["Reading","Grammar","Vocabulary","Writing","Literature"],
        7:["Reading Skills","Grammar","Vocabulary","Essay","Literature"],
        8:["Comprehension","Grammar","Vocabulary","Writing","Literature"],
        9:["Reading","Grammar","Vocabulary","Writing","Prose and Poetry"],
        10:["Comprehension","Grammar","Vocabulary","Writing","Prose Poetry Drama"],
      },
      hindi: {
        6:["कविता","गद्य","व्याकरण","लेखन"],
        7:["कविता","गद्य","व्याकरण","निबंध"],
        8:["कविता","गद्य","व्याकरण","पत्र लेखन"],
        9:["कविता","गद्य","नाटक","व्याकरण","लेखन"],
        10:["कविता","गद्य","नाटक","व्याकरण","लेखन","भाषा अभ्यास"],
      },
    },
  },
  westbengal: {
    subjects: [
      { id:"maths",   label:"Mathematics",   emoji:"➗" },
      { id:"science", label:"Science",        emoji:"🔬" },
      { id:"history", label:"History",        emoji:"📜" },
      { id:"geo",     label:"Geography",      emoji:"🗺️" },
      { id:"english", label:"English",        emoji:"📝" },
      { id:"bengali", label:"Bengali",        emoji:"🌸" },
    ],
    topics: {
      maths: {
        6:["Numbers","Integers","Fractions","Decimals","Algebra","Geometry","Mensuration","Data Handling"],
        7:["Integers","Fractions","Equations","Lines and Angles","Triangles","Algebraic Expressions","Mensuration"],
        8:["Rational Numbers","Algebra","Geometry","Mensuration","Statistics","Exponents"],
        9:["Real Numbers","Polynomials","Linear Equations","Triangles","Statistics","Surface Areas"],
        10:["Real Numbers","Quadratic Equations","Arithmetic Progressions","Triangles","Trigonometry","Statistics","Probability","Mensuration"],
      },
      science: {
        6:["Food","Materials","Changes","Plants","Body","Motion","Light","Electricity","Water","Air"],
        7:["Nutrition","Heat","Acids Bases","Changes","Weather","Soil","Motion","Light"],
        8:["Crop Production","Microorganisms","Metals","Combustion","Cell","Force","Sound","Pollution"],
        9:["Matter","Atoms","Cell","Tissues","Motion","Force","Gravitation","Work Energy"],
        10:["Chemical Reactions","Acids Bases Salts","Metals","Carbon","Periodic Table","Life Processes","Reproduction","Light","Electricity","Environment"],
      },
      history: {
        6:["Ancient Bengal","Early Civilisations","Vedic Period","Mauryan Empire"],
        7:["Medieval Bengal","Delhi Sultanate","Mughal Empire","Bhakti Movement"],
        8:["Modern India","British Rule","Reform Movements","Freedom Struggle"],
        9:["French Revolution","Russian Revolution","Rise of Nationalism","Bengal in Modern Age"],
        10:["World War I and II","India Independence","Cold War","Post-Independence India"],
      },
      geo: {
        6:["The Earth","Maps","Landforms","Water Bodies","Climate","India Overview"],
        7:["Atmosphere","Precipitation","Natural Vegetation","West Bengal Geography"],
        8:["Resources","Agriculture","Industries","Transport"],
        9:["India: Physical Features","India: Climate","India: Rivers","West Bengal Economy"],
        10:["Economic Geography","India: Agriculture","India: Industries","West Bengal Development"],
      },
      english: {
        6:["Reading","Grammar","Vocabulary","Writing","Literature"],
        7:["Reading Skills","Grammar","Vocabulary","Essay","Literature"],
        8:["Comprehension","Grammar","Vocabulary","Writing","Literature"],
        9:["Reading","Grammar","Vocabulary","Writing","Prose and Poetry"],
        10:["Comprehension","Grammar","Vocabulary","Writing","Prose Poetry Drama"],
      },
      bengali: {
        6:["কবিতা","গদ্য","ব্যাকরণ","রচনা"],
        7:["কবিতা","গদ্য","ব্যাকরণ","প্রবন্ধ"],
        8:["কবিতা","গদ্য","ব্যাকরণ","পত্র"],
        9:["কবিতা","গদ্য","নাটক","ব্যাকরণ","রচনা"],
        10:["কবিতা","গদ্য","নাটক","ব্যাকরণ","রচনা","ভাষা"],
      },
    },
  },
};

export const GRADES = [6,7,8,9,10,11,12].map(g=>({ id:`${g}`, label:`Class ${g}` }));

export const CURRICULUM = {
  cbse: {
    subjects: [
      { id:"maths",   label:"Mathematics", emoji:"➗" },
      { id:"science", label:"Science",     emoji:"🔬" },
      { id:"english", label:"English",     emoji:"📝" },
      { id:"social",  label:"Social Science", emoji:"🌍" },
    ],
    topics: {
      maths: {
        6:  ["Knowing Our Numbers","Whole Numbers","Playing with Numbers","Basic Geometrical Ideas","Understanding Elementary Shapes","Integers","Fractions","Decimals","Data Handling","Mensuration","Algebra","Ratio and Proportion"],
        7:  ["Integers","Fractions and Decimals","Data Handling","Simple Equations","Lines and Angles","The Triangle and Its Properties","Congruence of Triangles","Comparing Quantities","Rational Numbers","Practical Geometry","Perimeter and Area","Algebraic Expressions","Exponents and Powers"],
        8:  ["Rational Numbers","Linear Equations in One Variable","Understanding Quadrilaterals","Practical Geometry","Data Handling","Squares and Square Roots","Cubes and Cube Roots","Comparing Quantities","Algebraic Expressions","Exponents and Powers","Direct and Inverse Proportions","Factorisation","Introduction to Graphs","Playing with Numbers"],
        9:  ["Number Systems","Polynomials","Coordinate Geometry","Linear Equations in Two Variables","Introduction to Euclid Geometry","Lines and Angles","Triangles","Quadrilaterals","Areas of Parallelograms","Circles","Constructions","Heron's Formula","Surface Areas and Volumes","Statistics","Probability"],
        10: ["Real Numbers","Polynomials","Pair of Linear Equations","Quadratic Equations","Arithmetic Progressions","Triangles","Coordinate Geometry","Introduction to Trigonometry","Some Applications of Trigonometry","Circles","Constructions","Areas Related to Circles","Surface Areas and Volumes","Statistics","Probability"],
        11: ["Sets","Relations and Functions","Trigonometric Functions","Principle of Mathematical Induction","Complex Numbers","Linear Inequalities","Permutations and Combinations","Binomial Theorem","Sequences and Series","Straight Lines","Conic Sections","Introduction to 3D Geometry","Limits and Derivatives","Mathematical Reasoning","Statistics","Probability"],
        12: ["Relations and Functions","Inverse Trigonometric Functions","Matrices","Determinants","Continuity and Differentiability","Applications of Derivatives","Integrals","Applications of Integrals","Differential Equations","Vector Algebra","Three Dimensional Geometry","Linear Programming","Probability"],
      },
      science: {
        6:  ["Food: Where Does It Come From","Components of Food","Fibre to Fabric","Sorting Materials into Groups","Separation of Substances","Changes Around Us","Getting to Know Plants","Body Movements","The Living Organisms","Motion and Measurement","Light Shadows and Reflections","Electricity and Circuits","Fun with Magnets","Water","Air Around Us","Garbage In Garbage Out"],
        7:  ["Nutrition in Plants","Nutrition in Animals","Fibre to Fabric","Heat","Acids Bases and Salts","Physical and Chemical Changes","Weather Climate and Adaptations","Winds Storms and Cyclones","Soil","Respiration in Organisms","Transportation in Animals and Plants","Reproduction in Plants","Motion and Time","Electric Current","Light","Water: A Precious Resource","Forests","Wastewater Story"],
        8:  ["Crop Production and Management","Microorganisms","Synthetic Fibres and Plastics","Materials: Metals and Non-Metals","Coal and Petroleum","Combustion and Flame","Conservation of Plants and Animals","Cell Structure and Functions","Reproduction in Animals","Reaching the Age of Adolescence","Force and Pressure","Friction","Sound","Chemical Effects of Electric Current","Some Natural Phenomena","Light","Stars and the Solar System","Pollution of Air and Water"],
        9:  ["Matter in Our Surroundings","Is Matter Around Us Pure","Atoms and Molecules","Structure of the Atom","The Fundamental Unit of Life","Tissues","Diversity in Living Organisms","Motion","Force and Laws of Motion","Gravitation","Work and Energy","Sound","Why Do We Fall Ill","Natural Resources","Improvement in Food Resources"],
        10: ["Chemical Reactions and Equations","Acids Bases and Salts","Metals and Non-metals","Carbon and Its Compounds","Periodic Classification","Life Processes","Control and Coordination","How Do Organisms Reproduce","Heredity and Evolution","Light: Reflection and Refraction","Human Eye and Colourful World","Electricity","Magnetic Effects of Electric Current","Sources of Energy","Our Environment","Management of Natural Resources"],
        11: ["Physical World","Units and Measurements","Motion in a Straight Line","Motion in a Plane","Laws of Motion","Work Energy and Power","System of Particles","Gravitation","Mechanical Properties of Solids","Mechanical Properties of Fluids","Thermal Properties of Matter","Thermodynamics","Kinetic Theory","Oscillations","Waves","Electric Charges and Fields","Electrostatic Potential","Current Electricity","Moving Charges and Magnetism","Magnetism and Matter","Electromagnetic Induction","Alternating Current","Electromagnetic Waves","Ray Optics","Wave Optics","Dual Nature of Radiation","Atoms","Nuclei","Semiconductor Electronics"],
        12: ["Electric Charges and Fields","Electrostatic Potential and Capacitance","Current Electricity","Moving Charges and Magnetism","Magnetism and Matter","Electromagnetic Induction","Alternating Current","Electromagnetic Waves","Ray Optics and Optical Instruments","Wave Optics","Dual Nature of Radiation and Matter","Atoms","Nuclei","Semiconductor Electronics","Communication Systems"],
      },
      english: {
        6:  ["Who Did Patrick's Homework","How the Dog Found Himself a New Master","Taro's Reward","An Indian American Woman in Space","A Different Kind of School","Who I Am","Fair Play","A Game of Chance","Desert Animals","The Banyan Tree"],
        7:  ["Three Questions","A Gift of Chappals","Gopal and the Hilsa Fish","The Ashes That Made Trees Bloom","Quality","Expert Detectives","The Invention of Vita-Wonk","Fire: Friend and Foe","A Bicycle in Good Repair","The Story of Cricket"],
        8:  ["The Best Christmas Present in the World","The Tsunami","Glimpses of the Past","Bepin Choudhury's Lapse of Memory","The Summit Within","This is Jody's Fawn","A Visit to Cambridge","A Short Monsoon Diary","The Great Stone Face"],
        9:  ["The Fun They Had","The Sound of Music","The Little Girl","A Truly Beautiful Mind","The Snake and the Mirror","My Childhood","Packing","Reach for the Top","The Bond of Love","Kathmandu","If I Were You"],
        10: ["A Letter to God","Nelson Mandela","Two Stories About Flying","From the Diary of Anne Frank","Glimpses of India","Mijbil the Otter","Madam Rides the Bus","The Sermon at Benares","The Proposal"],
        11: ["The Portrait of a Lady","A Photograph","We're Not Afraid to Die","Discovering Tut","Landscape of the Soul","The Browning Version","The Adventure","Silk Road","Father to Son","The Laburnum Top","The Voice of the Rain","Childhood","Birth","The Tale of Melon City"],
        12: ["The Last Lesson","Lost Spring","Deep Water","The Rattrap","Indigo","Poets and Pancakes","The Interview","Going Places","My Mother at Sixty Six","An Elementary School Classroom","Keeping Quiet","A Thing of Beauty","A Roadside Stand","Aunt Jennifer's Tigers","The Tiger King","The Enemy","On the Face of It","Memories of Childhood"],
      },
      social: {
        6:  ["What Where How and When","On the Trail of the Earliest People","From Gathering to Growing Food","In the Earliest Cities","What Books and Burials Tell Us","Kingdoms Kings and an Early Republic","New Questions and Ideas","Ashoka the Emperor","Vital Villages Thriving Towns","Traders Kings and Pilgrims","New Empires and Kingdoms","Buildings Paintings and Books"],
        7:  ["Tracing Changes Through a Thousand Years","New Kings and Kingdoms","The Delhi Sultans","The Mughal Empire","Rulers and Buildings","Towns Traders and Craftspersons","Tribes Nomads and Settled Communities","Devotional Paths to the Divine","The Making of Regional Cultures","Eighteenth Century Political Formations"],
        8:  ["How When and Where","From Trade to Territory","Ruling the Countryside","Tribals Dikus and the Vision of a Golden Age","When People Rebel","Weavers Iron Smelters and Factory Owners","Civilising the Native Educating the Nation","Women Caste and Reform","The Making of the National Movement","India After Independence"],
        9:  ["The French Revolution","Socialism in Europe and the Russian Revolution","Nazism and the Rise of Hitler","Forest Society and Colonialism","Pastoralists in the Modern World","Peasants and Farmers","History and Sport","Clothing A Social History"],
        10: ["The Rise of Nationalism in Europe","Nationalism in India","The Making of a Global World","The Age of Industrialisation","Print Culture and the Modern World","Work Life and Leisure","Lifelines of National Economy","Resources and Development","Forest and Wildlife Resources","Water Resources","Agriculture","Mineral and Energy Resources","Manufacturing Industries","Political Parties","Outcomes of Democracy","Challenges to Democracy"],
        11: ["Indian Constitution at Work","Political Theory","Introducing Sociology","Understanding Society","Physical Geography","India Physical Environment","Introducing Microeconomics","Introducing Macroeconomics","Themes in World History","Themes in Indian History Part I"],
        12: ["Contemporary World Politics","Politics in India Since Independence","Indian Society","Social Change and Development","Fundamentals of Physical Geography","India People and Economy","Microeconomics","Macroeconomics","Themes in World History Part III","Themes in Indian History Part III"],
      },
    },
  },
  icse: {
    subjects: [
      { id:"maths",   label:"Mathematics", emoji:"➗" },
      { id:"physics", label:"Physics",     emoji:"⚡" },
      { id:"chemistry",label:"Chemistry",  emoji:"🧪" },
      { id:"biology", label:"Biology",     emoji:"🌿" },
      { id:"english", label:"English",     emoji:"📝" },
      { id:"history", label:"History & Civics", emoji:"🏛️" },
      { id:"geography",label:"Geography",  emoji:"🗺️" },
    ],
    topics: {
      maths: {
        6:  ["Number System","Fractions","Decimals","Ratio and Proportion","Percentage","Profit and Loss","Simple Interest","Sets","Basic Algebra","Geometry Basics","Mensuration","Data Handling"],
        7:  ["Integers","Fractions and Decimals","Exponents","Algebraic Expressions","Linear Equations","Ratio Proportion and Unitary Method","Percentage","Profit Loss and Discount","Simple and Compound Interest","Lines and Angles","Triangles","Symmetry","Mensuration","Data Handling"],
        8:  ["Rational Numbers","Exponents and Radicals","Algebraic Expressions","Factorisation","Linear Equations","Percentage","Profit and Loss","Simple and Compound Interest","Time and Work","Quadrilaterals","Construction of Quadrilaterals","Circles","Area and Perimeter","Volume and Surface Area","Data Handling","Probability"],
        9:  ["Pure Arithmetic","Commercial Mathematics","Algebra","Geometry","Statistics","Mensuration","Trigonometry","Coordinate Geometry"],
        10: ["Commercial Mathematics","Algebra","Geometry","Mensuration","Trigonometry","Statistics","Probability","Coordinate Geometry"],
        11: ["Sets and Functions","Algebra","Coordinate Geometry","Calculus","Mathematical Reasoning","Statistics and Probability","Relations and Functions","Trigonometry","Matrices"],
        12: ["Relations and Functions","Algebra","Calculus","Vectors and 3D Geometry","Linear Programming","Probability","Differential Equations","Applications of Integrals"],
      },
      physics: {
        6:  ["Matter and Its Composition","Physical Quantities and Measurement","Force","Light","Magnetism","Electricity"],
        7:  ["Physical Quantities and Measurement","Motion","Energy","Light","Sound","Heat","Electricity and Magnetism"],
        8:  ["Matter","Physical Quantities","Force and Pressure","Energy","Light","Sound","Electricity","Magnetism"],
        9:  ["Measurements and Experimentation","Motion in One Dimension","Laws of Motion","Pressure","Flotation","Work Energy and Power","Refraction of Light","Current Electricity","Magnetism"],
        10: ["Force","Work Energy and Power","Machines","Refraction of Light at Plane Surfaces","Refraction through Lenses","Spectrum","Sound","Electricity","Electromagnetism","Calorimetry","Radioactivity"],
        11: ["Physical World and Measurement","Kinematics","Laws of Motion","Work Energy Power","Motion of System of Particles","Gravitation","Properties of Bulk Matter","Thermodynamics","Behaviour of Perfect Gas","Oscillations and Waves"],
        12: ["Electrostatics","Current Electricity","Magnetic Effects of Current","Electromagnetic Induction","Alternating Currents","Electromagnetic Waves","Optics","Dual Nature of Matter","Atoms and Nuclei","Electronic Devices","Communication Systems"],
      },
      chemistry: {
        6:  ["Matter and Its Composition","Elements Compounds and Mixtures","Separation of Mixtures","Atoms and Molecules","Language of Chemistry","Water"],
        7:  ["Matter","Elements Compounds Mixtures","Atomic Structure","Language of Chemistry","Chemical Reactions","Acids Bases and Salts","Air and Atmosphere","Water"],
        8:  ["Matter","Atomic Structure","Language of Chemistry","Chemical Reactions","Hydrogen","Water","Carbon and Its Compounds","Sulphur","Nitrogen and Its Compounds","Metals and Non-metals"],
        9:  ["The Language of Chemistry","Chemical Changes and Reactions","Water","Atomic Structure","The Periodic Table","Study of the First Element Hydrogen","Study of Gas Laws","Atmospheric Pollution"],
        10: ["Periodic Properties","Chemical Bonding","Study of Acids Bases and Salts","Analytical Chemistry","Mole Concept","Electrolysis","Metallurgy","Study of Compounds","Organic Chemistry","Practical Chemistry"],
        11: ["Some Basic Concepts of Chemistry","Structure of Atom","Classification of Elements","Chemical Bonding","States of Matter","Thermodynamics","Equilibrium","Redox Reactions","Hydrogen","s-Block Elements","p-Block Elements","Organic Chemistry Basics","Hydrocarbons","Environmental Chemistry"],
        12: ["The Solid State","Solutions","Electrochemistry","Chemical Kinetics","Surface Chemistry","General Principles of Isolation","p-Block Elements","d and f Block Elements","Coordination Compounds","Haloalkanes and Haloarenes","Alcohols Phenols and Ethers","Aldehydes Ketones","Amines","Biomolecules","Polymers","Chemistry in Everyday Life"],
      },
      biology: {
        6:  ["The Cell","Tissues","Organ Systems","Photosynthesis","Nutrition","Respiration","Transportation","Excretion","Reproduction","Health and Disease"],
        7:  ["Tissue Organisation","Nutrition","Respiration","Excretion","Nervous System","Endocrine System","Reproduction","Heredity","Environment"],
        8:  ["Transportation in Plants","Transpiration","Photosynthesis","Respiration","Excretion","Nervous System","Endocrine System","Reproduction","Genetics","Ecosystems"],
        9:  ["Cell: The Unit of Life","Tissue","Flower","Pollination and Fertilisation","Seeds","Respiration in Plants","Five Kingdom Classification","Economic Importance of Bacteria and Fungi","Nutrition","Digestive System","Respiratory System","Circulatory System","Excretory System","Nervous System","Sense Organs","Endocrine System","Reproductive System"],
        10: ["Cell Division","Genetics","Absorption by Roots","Transpiration","Photosynthesis","Chemical Coordination in Plants","The Circulatory System","The Excretory System","The Nervous System","The Endocrine System","Reproduction","Human Evolution","Population","Pollution"],
        11: ["Diversity in Living World","Structural Organisation in Plants and Animals","Cell: Structure and Function","Plant Physiology","Human Physiology"],
        12: ["Reproduction","Genetics and Evolution","Biology in Human Welfare","Biotechnology","Ecology and Environment"],
      },
      english: {
        6:  ["The Selfish Giant","Robinson Crusoe","Gulliver's Travels","The Wind in the Willows","Poetry Appreciation","Grammar and Composition"],
        7:  ["Short Stories","Novel Study","Poetry","Drama","Grammar","Composition and Writing"],
        8:  ["Prose and Short Stories","Poetry","Drama","Novel","Grammar and Usage","Composition"],
        9:  ["Prose","Poetry","Drama","Grammar","Composition","Directed Writing"],
        10: ["Prose","Poetry","Drama","Grammar","Composition","Directed Writing","Literature"],
        11: ["Prose and Short Stories","Poetry Appreciation","Drama","Novel Study","Grammar and Usage","Creative Writing","Directed Writing"],
        12: ["Prose","Poetry","Drama","Novel","Grammar","Composition","Directed Writing","Literature in English"],
      },
      history: {
        6:  ["Ancient Civilisations","The River Valley Civilisations","Ancient India","The Vedic Period","Religions of Ancient India","The Mauryan Empire","The Gupta Empire"],
        7:  ["Medieval India","The Sultanate Period","The Mughal Empire","Bhakti Movement","Medieval Europe","The Renaissance","The Reformation"],
        8:  ["Modern India","The British Conquest","Social and Religious Reform","The Freedom Struggle","The Indian National Congress","Non-Cooperation Movement","Independence and Partition"],
        9:  ["The Harappan Civilisation","The Vedic Period","Jainism and Buddhism","The Mauryan Empire","The Age of the Guptas","Medieval India","The Mughal Empire","European History"],
        10: ["The Outbreak of World War I","The Russian Revolution","The Rise of Totalitarianism","World War II","The United Nations","India's Freedom Struggle","Civics and Government"],
        11: ["Early Societies","Empires","Changing Traditions","Paths to Modernisation","Political Science: Constitution","Rights in the Indian Constitution","Election and Representation","Executive","Legislature","Judiciary"],
        12: ["Themes in World History: Colonialism","Themes in World History: Cold War Era","Contemporary India: Challenges","Politics in India: Party System","Political Science: Security","Environment and Natural Resources","Globalisation"],
      },
      geography: {
        6:  ["The Earth in the Solar System","Latitudes and Longitudes","Motions of the Earth","Maps","Major Domains of the Earth","Major Landforms","India: Location and Extent"],
        7:  ["Environment","Natural Vegetation","Wildlife","Human Environment","Air","Water","Natural Disasters"],
        8:  ["Resources","Land Soil Water Natural Vegetation and Wildlife","Agriculture","Industries","Human Resources"],
        9:  ["Lithosphere","Hydrosphere","Atmosphere","Natural Vegetation","Map Work","India: Drainage","India: Climate","India: Natural Vegetation","India: Soils"],
        10: ["Geographical Thought","Weathering and Mass Wasting","River Landforms","Glacial Landforms","India: Population","India: Agriculture","India: Industries","India: Transport and Communication","Environmental Concerns"],
        11: ["Physical Geography: Earth","Physical Geography: Atmosphere","Physical Geography: Water","Physical Geography: Biosphere","Human Geography: People","Human Geography: Human Activities","Practical Work in Geography"],
        12: ["Human Geography: Planning","Transport Communication and Trade","International Trade","Geographical Perspective on Issues","India: People and Economy","India: Land Resources","India: Water Resources","India: Mineral and Energy Resources","India: Manufacturing Industries","India: Planning and Sustainable Development"],
      },
    },
  },
};
export const UNIT_STAGES = ["Introduction","Deep Dive","Challenge","Mastery"];
export const UNIT_ICONS  = ["📖","🔍","⚔️","🌍"];
export const UNIT_XP     = [60, 80, 150, 100];
// UNIT_COLORS defined in theme above

export const DIFFICULTIES = [
  { id:"easy",    label:"Easy",    emoji:"🌱", desc:"Basic concepts, straightforward questions",   color:"#22C55E", xp:20  },
  { id:"medium",  label:"Medium",  emoji:"⚡", desc:"Requires understanding and application",      color:"#F59E0B", xp:40  },
  { id:"hard",    label:"Hard",    emoji:"🔥", desc:"Multi-step problems and deeper thinking",     color:"#EF4444", xp:70  },
  { id:"extreme", label:"Extreme", emoji:"💀", desc:"Expert level — only for the brave!",          color:"#A855F7", xp:120 },
];

